/*
 * THIS CLASS WOULD BE THE OBJECT CLASS OF THE WHOLE ENTIRE PROGRAM, WHICH WOULD CONTAIN IF THE 
 * FOLLOWING BLOCK IS VISITED OR NOT
 * IF THE OBJECT IS BLOCKED THEN THE VALUE OF THAT OBJECT WOULD BE CHANGED TO 'O', IF IT IS NOT BLOCEKD
 * THEN IT WOULD BE 'X' 
 */
public class dataStructure {
	boolean visted = false;
	boolean blocked = false;
	char value = 'x';
}
